name: fluttershy
description: Experimental game engine written in Flutter.
version: 0.1.4
homepage: https://github.com/DavidDomkar/fluttershy

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  vector_math: ^2.0.8
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
